### ISSUE TITLE
Policy checklist reporting without setting up study region

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#274]
Users who complete a policy checklist should be able to generate a policy summary report directly, without requiring configuration of a region.  
- [ ] This could be executed like "$policy-summary [filename].xlsx" where the filename corresponds to a file in what is currently the data/policy_review sub-folder.  
- [ ] The policy checklist document will be read and assuming it has been completed with a required set of information (city name, etc), a PDF summary document will be compiled and exported to a '_policy_checklist_outputs' sub-folder in the data directory.
- [ ] Basic guidance could also be displayed for users to set up a spatial analysis with this policy checklist using the region configuration text file (but that's not necessary to prepare the policy checklist report).

Additionally, the 'policy_review' sub-folder and related language should be updated to refer to 'policy-checklist' or similar to be consistent with other resources, in all places where this is referred to.

**Comment by carlhiggs** [comment]
As per https://github.com/global-healthy-liveable-cities/global-indicators/commit/bbc836192f6a2b549fc7bf1450b2b05a4ef099a7, this has been implemented.  The policy checklist can be generated using the interactive web app interface - no typing required, a user chooses a file with the file picker and can display and interactively search their completed checklist.  They can also generate a comprehensively indexed PDF document by clicking a button.  This saves the file with the same name, changing xlsx to pdf.
