### ISSUE TITLE
Update report templates and methods to use new policy checklist tool

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#367]
The policy checklist has been updated, and we need to update the corresponding methods and templates to support reporting on results for the [1000 Cities Challenge](https://www.healthysustainablecities.org/1000cities).

**Describe the solution you'd like**
A completed policy checklist XLSX file can be read and a subset of policies reported on in the default indicators reporting templates, according to the new design.

Our collaborators @anaqueralt and @JaviMolina-Garcia have prepared a draft analysis for the example city of Las Palmas that we can use to prototype this feature.  @mdlowe has prepared a draft template which I have implemented some features of, and @eugenrb will also assist in refining this. 

This is part of a bigger effort to update reporting templates.

**Comment by carlhiggs** [comment]
A whole load of recent updates have addressed this on the Enhancements branch; I plan to merge these in and close this issue in April 2024, once designs are signed off on and translations finalised.

**Comment by carlhiggs** [comment]
Tasks/considerations from latest feedback round:
- [x] remove second 'may' from environmental disaster context
- [x] access plot legend in lower right
- [x] reference "(Box 1)" in access plot 
- [x] updated report title in recommended citation on final page
- [x] remove levels of government from spatial report
- [x] experiment with alternate Box 1 figure (or no figure?); ML suggested TLGH cover, ER suggested more readable text.  Could show 25 maps; but would be crowded….  Or table…
- [x] more space above 'Neighbourhood walkability relative to 25 cities internationally
- [x] Summary on last page of policy checklist
  - [ ]  requires finalisation, use and implementation of new checklist design
- [x] Study region map; configurable choice of basemap? (could resolve ER query below)
  - [ ] ER suggested labels; trouble is, with translation, these could display in incorrect language, but I will look into possibilities
- [x] Box 1 in policy and spatial reports if possible 
- [x] larger ticks if possible (like 1st table, at least ---ensure consistent)
- [ ] policy table after destinations access? I'm not sure actually, policy is the upstream determinent of the measured outcomes, I think makes sense to have first to detail context, and then the implications
