### ISSUE TITLE
Spring semester potential task list

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#374]
A potential list of tasks for Spring semester development work on the Global Healthy and Sustainable City Indicators tool, following discussion between @dapugacheva, @gboeing and myself:

- [ ] Follow directions for software usage at https://healthysustainablecities.github.io/software/ and evaluate experience
  - These directions are intended to make analysis and reporting of policy and spatial indicators for healthy and sustainable cities accessible to users from a diverse range of disciplines and background experience (e.g. urban planning, epidemiology, geography--- some may be focused more on policy than spatial analysis)
  - The current directions relate to the software main branch, however additional work has been undertaken on the 'enhancements' branch
  - Considerations include
    - Does analysis work as intended for the example city?
    - Does analysis work as intended for cities or sites in other contexts?  (may need to use custom data or alternate configurations)
    - Could the directions be improved to make usage easier?
- [ ] Propose 'vignettes' or short example guides for undertaking specific tasks (e.g. an analysis for a city in a distinct context or a user with distinct needs, to showcase aspects not covered in depth by the existing example
  - Examples of undertaking validation analyses are a priority 
    - Optionally, could explore implementing or re-integrating additional analysis and reporting functionality for validation analysis into the software
  - Example of using custom data
    - e.g. Geoff suggested  Overture Maps as our amenity/POI data source for accessibility analysis --- could code be modified to allow this as a configurable option?  Could a guide be created to illustrate 
      - why a user might want to configure alternative data
      - how this could be done
      - how a user could evaluate the impact of this methodological choice (e.g. comparing various aspects of spatial data quality and appropriateness for the analysis in question, using one dataset vs. another custom configured one)
- [ ] Implementing other requested additional functionality, e.g.
  - automated testing and retrievable of configured URLs (need to address safety concerns if doing this --- user responsibility to authorise download; very important if using a configuration file supplied by another person)
  - option to configure Overpass as a single source for infrastructure/POI retrieval (ie. instead of downloading .pbf file)
  - option to configure .pbf file as single source for all feature data (ie. extract network data from .pbf; currently network is retrieved via Overpass for a matching time point, meaning double handling of OpenStreetMap data)
  - option to configure an alternate network data source (eg if you have official pedestrian or cycling network data and want to use that) 

The above list contains a number of suggestions, roughly ordered in terms of complexity but not necessarily prioritised --- except that  the first steps involve familiarising oneself with the software and evaluating its usage with fresh eyes and for new contexts/situations.  This will be a great place to start, and feedback/contributions will be much appreciated!

We can refine the list and priorities over time as required, and in coordination with feedback from @global-healthy-liveable-cities/software-spatial

**Comment by dapugacheva** [comment]
The experience evaluation comments are stored here https://github.com/global-healthy-liveable-cities/global-indicators/issues/375#issue-2106971572. @rychennn you can add your comments as you test the software.

**Comment by carlhiggs** [comment]
This is historical, so will close this issue
