### ISSUE TITLE
GHSCI web app 'Policy checklist' menu should optionally load checklist for a configured region

### ISSUE THREAD

**Issue by carlhiggs** [healthysustainablecities/global-indicators#401]
**Is your feature request related to a problem? Please describe.**
Currently the web app 'Policy checklist' menu has a button that allows manual selection of a completed policy checklist.

![image](https://github.com/global-healthy-liveable-cities/global-indicators/assets/12984626/96b61834-05af-44d0-ac81-02aa206c5de8)

However, if a user has selected a configured study region (like the example region) the first option should be to display the configured checklist for that region.

**Describe the solution you'd like**

- [ ] Before providing the option to select a policy checklist file to view, if a configured region has been selected have a button to view its configured checklist directly.
- [ ] In addition to viewing the checklist, there should also be options to summarise and view formatted aspects of the checklist.
- [ ] Ultimately, there should be the option to generate a policy-only report, that if undertaken using the local file picker will generate a policy report like would otherwise be done for a configured region including images etc.
